#pragma once

#include "disconnect_compat.hpp"

#include <string>
#include <unordered_map>
#include <vector>

namespace duckdb {
namespace disconnect {

//! One (pattern, category, organization) triple of the generated list.
struct RawListEntry {
	const char *pattern;
	uint16_t category;
	uint32_t organization;
};

// Generated by scripts/generate_list_data.py, see src/generated/disconnect_data.cpp.
extern const char *const GENERATED_SOURCE_INFO;
extern const char *const GENERATED_CATEGORIES[];
extern const idx_t GENERATED_CATEGORY_COUNT;
extern const char *const GENERATED_ORG_NAMES[];
extern const char *const GENERATED_ORG_URLS[];
extern const idx_t GENERATED_ORG_COUNT;
extern const RawListEntry GENERATED_ENTRIES[];
extern const idx_t GENERATED_ENTRY_COUNT;

struct Organization {
	string name;
	string url;
};

//! A list entry as written in the source file, kept for disconnect_entries().
struct ListTriple {
	string pattern;
	uint16_t category;
	uint32_t organization;
};

//! A few entries scope a rule to a path prefix ("google.com/pagead/1p-user-list").
struct PathRule {
	string path;
	string pattern;
	uint64_t category_mask = 0;
	uint16_t category = 0;
	uint32_t organization = 0;
	//! Index into `triples` of the source line `category` came from.
	uint32_t entry_index = 0;
};

//! Everything the list knows about one host, merged across categories.
struct HostEntry {
	string host;
	bool has_host_rule = false;
	uint64_t category_mask = 0;
	uint16_t category = 0;
	uint32_t organization = 0;
	//! Index into `triples` of the source line `category` came from; only
	//! meaningful when `has_host_rule`.
	uint32_t entry_index = 0;
	vector<PathRule> path_rules;
};

struct MatchResult {
	const string *pattern = nullptr;
	uint64_t category_mask = 0;
	uint16_t category = 0;
	uint32_t organization = 0;
	//! Where the match sits in Triples(): the source line `category`,
	//! `organization` and `pattern` above describe. Hosts listed under several
	//! categories have one entry per category; this is the primary one.
	uint32_t entry_index = 0;
};

//! Every category bit set. What the describing functions — tracker_category(),
//! tracker_owner(), tracker_pattern() — look a URL up under, so they can still
//! report what the list says about a host that is_tracker() declines to call a
//! tracker.
static constexpr uint64_t ALL_CATEGORIES = ~uint64_t(0);

//! The category an unfiltered is_tracker() leaves out. Disconnect lists a
//! tracking company's own first-party properties under Content — google.com
//! and yandex.ru are both on it — and a browser does not block those, so
//! counting them made the one-argument is_tracker() answer a question nobody
//! was asking. Name it explicitly with the two-argument form to get it back.
static constexpr const char *EXCLUDED_BY_DEFAULT = "Content";

//! An immutable snapshot of a Disconnect services list, indexed for lookups.
class DisconnectList {
public:
	DisconnectList(const DisconnectList &) = delete;
	DisconnectList &operator=(const DisconnectList &) = delete;

	//! The list currently in use (the embedded one until disconnect_load() runs).
	static shared_ptr<const DisconnectList> Current();
	//! Install a list process-wide.
	static void Replace(shared_ptr<const DisconnectList> list);
	//! Reinstall the list embedded at build time.
	static shared_ptr<const DisconnectList> ResetToEmbedded();

	static shared_ptr<const DisconnectList> BuildEmbedded();
	//! Parse a disconnect_services.json document. Throws on malformed input.
	static shared_ptr<const DisconnectList> FromJson(const char *data, idx_t len, const string &source);

	//! Look up a URL or bare hostname. Matches the host itself and every parent
	//! domain, restricted to the categories in `filter_mask`.
	bool Match(const char *url, idx_t len, uint64_t filter_mask, MatchResult &result) const;

	//! The mask an unfiltered is_tracker() matches under: every category this
	//! list has except EXCLUDED_BY_DEFAULT. Equal to ALL_CATEGORIES when the
	//! loaded list has no such category.
	uint64_t DefaultCategoryMask() const {
		return default_mask;
	}

	//! Translate a comma-separated category list into a bitmask.
	//! Throws InvalidInputException on an unknown category name.
	uint64_t ParseCategoryFilter(const string &filter) const;

	const vector<string> &Categories() const {
		return categories;
	}
	const string &CategoryName(uint16_t index) const {
		return categories[index];
	}
	const Organization &Org(uint32_t index) const {
		return organizations[index];
	}
	const vector<ListTriple> &Triples() const {
		return triples;
	}
	const string &Source() const {
		return source;
	}
	idx_t HostCount() const {
		return hosts.size();
	}
	idx_t OrganizationCount() const {
		return organizations.size();
	}

private:
	DisconnectList() = default;

	//! Install the category names and compute their priority ranks.
	void SetCategories(vector<string> names);
	//! Register one source line; `pattern` must already be lowercase.
	void AddEntry(const string &pattern, uint16_t category, uint32_t organization);
	void BuildIndex();
	idx_t FindHost(const char *host, idx_t len) const;

	string source;
	vector<string> categories;
	vector<Organization> organizations;
	vector<ListTriple> triples;
	vector<HostEntry> hosts;
	//! Host name to index into `hosts`, only used while building.
	std::unordered_map<string, idx_t> host_lookup;
	//! Open-addressing map from host name to an index into `hosts`; a slot
	//! holds index + 1 so that 0 marks an empty slot.
	vector<uint32_t> buckets;
	uint64_t bucket_mask = 0;
	//! Rank of each category in `categories` for picking a primary category.
	vector<uint16_t> category_rank;
	//! ALL_CATEGORIES minus the EXCLUDED_BY_DEFAULT bit; see DefaultCategoryMask().
	uint64_t default_mask = ALL_CATEGORIES;
};

} // namespace disconnect
} // namespace duckdb
