#!/usr/bin/env python3
"""Generate the embedded Disconnect list (src/generated/disconnect_data.cpp).

Usage:
    python3 scripts/generate_list_data.py [path/to/disconnect_services.json]

The generated file is committed to the repository so that building the
extension does not require Python or the JSON file. Re-run `make regen-list`
after refreshing data/external/disconnect_services.json.

The embedded data is derived from the Disconnect services list, which is
licensed CC BY-NC-SA 4.0 (see the `license` field of the source JSON).
"""

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SOURCE = os.path.join(HERE, "..", "..", "data", "external", "disconnect_services.json")
OUT_PATH = os.path.join(HERE, "..", "src", "generated", "disconnect_data.cpp")


def c_string(value):
    out = []
    for ch in value:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            out.extend("\\%03o" % b for b in ch.encode("utf-8"))
    return '"%s"' % "".join(out)


def parse(source_path):
    with open(source_path, encoding="utf-8") as handle:
        doc = json.load(handle)

    categories = []
    category_index = {}
    orgs = []
    org_index = {}
    triples = []

    for category, entries in doc["categories"].items():
        if category not in category_index:
            category_index[category] = len(categories)
            categories.append(category)
        for entry in entries:
            for org_name, org_urls in entry.items():
                for org_url, patterns in org_urls.items():
                    # Property markers such as {"dnt": "eff"} or
                    # {"session-replay": "true"} carry a string instead of a
                    # list of domains; they are not blocklist entries.
                    if not isinstance(patterns, list):
                        continue
                    key = (org_name, org_url)
                    if key not in org_index:
                        org_index[key] = len(orgs)
                        orgs.append(key)
                    for pattern in patterns:
                        pattern = pattern.strip().lower().rstrip(".")
                        if not pattern:
                            continue
                        triples.append((pattern, category_index[category], org_index[key]))

    # Stable, de-duplicated output: sorting keeps diffs readable across refreshes.
    triples = sorted(set(triples))
    return categories, orgs, triples


def main():
    source_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE
    categories, orgs, triples = parse(source_path)

    with open(source_path, "rb") as handle:
        digest = hashlib.sha256(handle.read()).hexdigest()

    if len(categories) > 64:
        raise SystemExit("category bitmask is 64 bits wide; source has %d categories" % len(categories))

    lines = []
    add = lines.append
    add("// AUTO-GENERATED by scripts/generate_list_data.py -- do not edit by hand.")
    add("// Source: %s" % os.path.basename(source_path))
    add("// SHA-256: %s" % digest)
    add("// Entries: %d, organizations: %d, categories: %d" % (len(triples), len(orgs), len(categories)))
    add("//")
    add("// The data below is derived from the Disconnect services list,")
    add("// Copyright Disconnect, Inc., licensed under CC BY-NC-SA 4.0:")
    add("// https://creativecommons.org/licenses/by-nc-sa/4.0/")
    add("")
    add('#include "disconnect_list.hpp"')
    add("")
    add("namespace duckdb {")
    add("namespace disconnect {")
    add("")
    add("const char *const GENERATED_SOURCE_INFO = %s;" % c_string("%s sha256:%s" % (os.path.basename(source_path), digest[:16])))
    add("")
    add("const char *const GENERATED_CATEGORIES[] = {")
    for name in categories:
        add("    %s," % c_string(name))
    add("};")
    add("const idx_t GENERATED_CATEGORY_COUNT = %d;" % len(categories))
    add("")
    add("const char *const GENERATED_ORG_NAMES[] = {")
    for name, _ in orgs:
        add("    %s," % c_string(name))
    add("};")
    add("const char *const GENERATED_ORG_URLS[] = {")
    for _, url in orgs:
        add("    %s," % c_string(url))
    add("};")
    add("const idx_t GENERATED_ORG_COUNT = %d;" % len(orgs))
    add("")
    add("const RawListEntry GENERATED_ENTRIES[] = {")
    for pattern, category, org in triples:
        add("    {%s, %d, %d}," % (c_string(pattern), category, org))
    add("};")
    add("const idx_t GENERATED_ENTRY_COUNT = %d;" % len(triples))
    add("")
    add("} // namespace disconnect")
    add("} // namespace duckdb")
    add("")

    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    print("wrote %s (%d entries, %d organizations, %d categories)" % (
        os.path.relpath(OUT_PATH), len(triples), len(orgs), len(categories)))


if __name__ == "__main__":
    main()
